version: '3'

networks:
  laravel:

services:
  datepoll-nginx:
    image: nginx:stable-alpine
    container_name: datepoll-nginx
    ports:
      - "9130:9130"
      - "9110:9110"
    volumes:
      - ./code/backend:/backend:z
      - ./code/frontend:/frontend:z
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:z
      - ./config/security-headers.conf:/etc/nginx/security-headers.conf:z
    depends_on:
      - datepoll-php
      - datepoll-mysql
    networks:
      - laravel

  datepoll-mysql:
    image: mariadb:latest
    container_name: datepoll-mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql:z
    environment:
      MARIADB_USER: homestead
      MARIADB_DATABASE: homestead
      MARIADB_PASSWORD: homestead
    networks:
      - laravel

  datepoll-redis:
    container_name: datepoll-redis
    image: redis:alpine
    volumes:
      - ./redis:/data:z
    networks:
      - laravel

  datepoll-php:
    build:
      context: .
      dockerfile: phpDockerfile
    container_name: datepoll-php
    volumes:
      - ./code/backend:/backend:z
    networks:
      - laravel

  datepoll-worker-php:
    build:
      context: .
      dockerfile: phpDockerfile
    container_name: datepoll-worker-php
    command: php artisan horizon
    volumes:
      - ./code/backend:/backend:z
    networks:
      - laravel
    depends_on:
      - datepoll-redis  
